cat > sql/02_validation_queries.sql <<'EOF'
-- Quick validation queries for ANALYTICS_DB.OBG.VW_OBGYN_EXTRACTED

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

-- Row count
SELECT COUNT(*) AS n_rows
FROM ANALYTICS_DB.OBG.VW_OBGYN_EXTRACTED;

-- Document mix
SELECT DOCUMENTTYPE, COUNT(*) AS n
FROM ANALYTICS_DB.OBG.VW_OBGYN_EXTRACTED
GROUP BY 1
ORDER BY n DESC;

-- Patient class mix
SELECT PATIENTCLASS, COUNT(*) AS n
FROM ANALYTICS_DB.OBG.VW_OBGYN_EXTRACTED
GROUP BY 1
ORDER BY n DESC;

-- Age extraction completeness
SELECT
  COUNT(*) AS n,
  AVG(IFF(EXTRACTED_AGE IS NULL, 1, 0)) AS pct_age_missing
FROM ANALYTICS_DB.OBG.VW_OBGYN_EXTRACTED;

-- Preview
SELECT *
FROM ANALYTICS_DB.OBG.VW_OBGYN_EXTRACTED
LIMIT 20;
EOF
